
development:
  adapter: postgresql
  encoding: unicode
  database: tunr_app_development
  pool: 5
  username: niznik
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: tunr_app_test
  pool: 5
  username: niznik
  password:
